version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swordfish-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - swordfish-network

networks:
  swordfish-network:
    driver: bridge

